# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Download/pipeline_CPU2/pipeline_CPU2.cache/wt [current_project]
set_property parent.project_path C:/Download/pipeline_CPU2/pipeline_CPU2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files {{C:/Users/YY  WYX/Desktop/test/1_addi.hex.coe}}
add_files -quiet c:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/ip/imem/imem.dcp
set_property used_in_implementation false [get_files c:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/ip/imem/imem.dcp]
read_verilog -library xil_defaultlib {
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/imports/8_pipeline_cpu/adder.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/imports/8_pipeline_cpu/multiply.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/imports/8_pipeline_cpu/alu.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/imports/8_pipeline_cpu/wb.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/imports/8_pipeline_cpu/exe.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/imports/8_pipeline_cpu/mem.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/imports/8_pipeline_cpu/fetch.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/imports/8_pipeline_cpu/decode.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/new/data_ram.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/imports/8_pipeline_cpu/regfile.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/new/clk_divider.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/imports/8_pipeline_cpu/pipeline_cpu.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/new/seg.v
  C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/sources_1/imports/sources_1/imports/8_pipeline_cpu/pipeline_cpu_display.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/constrs_1/imports/new/1.xdc
set_property used_in_implementation false [get_files C:/Download/pipeline_CPU2/pipeline_CPU2.srcs/constrs_1/imports/new/1.xdc]


synth_design -top pipeline_cpu_display -part xc7a100tcsg324-1


write_checkpoint -force -noxdef pipeline_cpu_display.dcp

catch { report_utilization -file pipeline_cpu_display_utilization_synth.rpt -pb pipeline_cpu_display_utilization_synth.pb }
